# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-08 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('firedate', models.DateField()),
                ('hiredate', models.DateField()),
                ('position', models.CharField(max_length=50)),
                ('fulltime', models.BooleanField()),
                ('empid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=3)),
                ('zip', models.IntegerField()),
                ('street', models.CharField(max_length=50)),
                ('storenum', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbackary.location'),
        ),
    ]
