# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-08 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbbackary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='receipts',
            fields=[
                ('receiptnumber', models.AutoField(primary_key=True, serialize=False)),
                ('weekend', models.DateField()),
                ('iscash', models.BooleanField()),
                ('saledate', models.BooleanField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbackary.employee')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbackary.location')),
            ],
            options={
                'db_table': 'receipts',
            },
        ),
    ]
