# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-08 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbbackary', '0005_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='quantidade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
