# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-08 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbbackary', '0006_items_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codcat', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'conteudo',
            },
        ),
        migrations.CreateModel(
            name='Cozinheiro',
            fields=[
                ('cpf', models.AutoField(primary_key=True, serialize=False)),
                ('nomefantasia', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cozinheiro',
            },
        ),
        migrations.CreateModel(
            name='Degustador',
            fields=[
                ('cpf', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'degustador',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('cpf', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('dataingresso', models.DateField()),
                ('salario', models.FloatField()),
            ],
            options={
                'db_table': 'funcionario',
            },
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('codingr', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ingredientes',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('isbn', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'livro',
            },
        ),
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('codrec', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('nroporcoes', models.IntegerField()),
                ('tempopreparo', models.CharField(max_length=50)),
                ('grau', models.IntegerField(blank=True, null=True)),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=150)),
                ('codcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbackary.Categoria')),
                ('cpfcoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbackary.Cozinheiro')),
                ('idgood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbackary.Ingredientes')),
            ],
            options={
                'db_table': 'receitas',
            },
        ),
        migrations.CreateModel(
            name='TesteReceita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nota', models.IntegerField(max_length=150)),
                ('codrec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbackary.Receitas')),
                ('cpfdeg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbackary.Degustador')),
            ],
            options={
                'db_table': 'teste_receita',
            },
        ),
        migrations.AddField(
            model_name='conteudo',
            name='codrec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbackary.Receitas'),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbbackary.Livro'),
        ),
    ]
