# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-08 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbbackary', '0007_auto_20171208_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='data',
            field=models.CharField(max_length=50),
        ),
    ]
