# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-08 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbbackary', '0008_auto_20171208_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='cozinheiro',
            name='especialidade',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cozinheiro',
            name='nomefantasia',
            field=models.CharField(max_length=50),
        ),
    ]
