# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-08 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbbackary', '0012_auto_20171208_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='goods_id',
        ),
        migrations.RemoveField(
            model_name='items',
            name='receipts_id',
        ),
        migrations.DeleteModel(
            name='items',
        ),
    ]
