insert into categoria values (1, 'bolos');
insert into categoria values (2, 'risotos');
insert into categoria values (3, 'pudins');
insert into categoria values (4, 'paes');
insert into categoria values (5, 'massas');
insert into categoria values (6, 'biscoitos');
insert into categoria values (7, 'sopas');
insert into categoria values (8, 'carnes');
insert into categoria values (9, 'sobremesas');
insert into categoria values (10, 'saladas');
insert into categoria values (11, 'frituras');
insert into categoria values (12, 'tortas');
insert into categoria values (13, 'peixes');
insert into categoria values (14, 'bebidas');
insert into categoria values (15, 'frutos do mar');
insert into categoria values (16, 'salgados');
insert into categoria values (17, 'pratos principais vegetarianos');
insert into categoria values (18, 'petiscos');
insert into categoria values (19, 'aperitivos');
insert into categoria values (20, 'massas');
insert into categoria values (21, 'bebidas');
insert into categoria values (22, 'molhos');
