insert into ingredientes values (100, 'farinha de trigo', 'farinha branca');
insert into ingredientes values (101, 'farinha de milho', ' ');
insert into ingredientes values (102, 'farinha de arroz', ' ');
insert into ingredientes values (103, 'ovos', ' ');
insert into ingredientes values (104, 'manteiga', 'sem sal');,
insert into ingredientes values (105, ' oleo',' ');
insert into ingredientes values (106, 'acucar branco', ' ');
insert into ingredientes values (107, 'acucar mascavo', ' ');
insert into ingredientes values (108, 'adocante', ' ');
insert into ingredientes values (109, 'claras de ovos', ' ');
insert into ingredientes values (110, 'gemas de ovos', ' ');
insert into ingredientes values (111, 'fermento em po', ' ');
insert into ingredientes values (112, 'fermento biologico', ' ');
insert into ingredientes values (113, 'chocolate em po', ' ');
insert into ingredientes values (114, 'achocolatado', ' ');
insert into ingredientes values (115, 'leite condensado', ' ');
insert into ingredientes values (121, 'arroz branco', ' ');
insert into ingredientes values (122, 'arroz arboreo', ' ');
insert into ingredientes values (123, 'arroz integral', ' ');
insert into ingredientes values (131, 'espaguete', ' ');
insert into ingredientes values (132, 'macarrao', ' ');
insert into ingredientes values (133, 'fusili', ' ');
insert into ingredientes values (140, 'tomate', ' ');
insert into ingredientes values (141, 'cebola', ' ');
insert into ingredientes values (142, 'alho', ' ');
insert into ingredientes values (143, 'tempero verde', ' ');
insert into ingredientes values (144, 'cenoura', ' ');
insert into ingredientes values (145, 'moranga', ' ');
insert into ingredientes values (146, ' abobrinha', ' ');
insert into ingredientes values (147, 'manjericao', ' ');
insert into ingredientes values (148, 'batata inglesa', ' ');
insert into ingredientes values (149, 'batata doce', ' ');
insert into ingredientes values (150, 'queijo ralado', ' ');
insert into ingredientes values (151, 'queijo prato', ' ');
insert into ingredientes values (152, 'queijo mussarela', ' ');
insert into ingredientes values (160, 'peito de frango', ' ');
insert into ingredientes values (161, 'asa de frango', ' ');
insert into ingredientes values (162, 'coxa de frango', ' ');
insert into ingredientes values (163, 'peixe', ' ');
insert into ingredientes values (164, ' agua', 'da torneira');
insert into ingredientes values (165, 'leite', ' ');
insert into ingredientes values (166, 'alface', ' ');
insert into ingredientes values (167, 'aveia', 'comum');
insert into ingredientes values (168, 'cevada', ' ');
insert into ingredientes values (169, 'quinoa', ' ');
insert into ingredientes values (170, 'sagu', 'brasileiro');
insert into ingredientes values (171, 'trigo', 'sarraceno');
insert into ingredientes values (172, 'cogumelo', 'seco');
insert into ingredientes values (173, 'salsa', '');
insert into ingredientes values (174, 'arroz','para risotto');
insert into ingredientes values (175, 'agua', 'da torneira');
insert into ingredientes values (176, 'caldo', 'de legumes');
insert into ingredientes values (177, 'sal', '');
insert into ingredientes values (178, 'queijo parmesao','ralado');
insert into ingredientes values (179, 'leite','');
insert into ingredientes values (180, 'grao de bico','natural');
insert into ingredientes values (181,'limão','bergamota');
insert into ingredientes values (182,'beringela'.'');
insert into ingredientes values (183,'Granulado','colorido');
insert into ingredientes values (184,'cebolinha','');
